config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resource :dashboard

  resources :orders, only: %w+index show unlock cancelleds+ do
    member do
      get :unlock
    end

    collection do
      get :cancelleds
    end
  end
  root to: 'dashboards#show'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/concerns/notifiable.rb
module Notifiable
  extend ActiveSupport::Concern

  included do
    has_many :log_items, as: :loggable
  end

  def log_all_action
    puts 'action'
  end
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :order
  has_many :invoice_items
end

app/models/invoice_item.rb
class InvoiceItem < ApplicationRecord
  belongs_to :invoice
  
end

app/models/log_item.rb
class LogItem < ApplicationRecord
  belongs_to :loggable, polymorphic: true
end

app/models/order.rb
class Order < ApplicationRecord
  include Notifiable

  has_many :order_items
  has_one :invoice

  before_save :generate_number

  state_machine :state, initial: :pending do
    before_transition from: :pending, to: :cancelled, do: :notify_admin

    event :enable do
      transition [:pending,:cancelled] => :enabled
    end

    event :cancel do
      transition [:pending, :enabled, :invoiced] => :cancelled
    end
  end

  private
    def generate_number
      self.number = 'O-'+(Order.count +1).to_s
    end

    def generate_invoice
      i = self.create_invoice
      self.order_items.each do |order_item|
        i.invoice_items.create order_item.attributes.delete_if{ |k,v| %w(order_id created_at updated_at).include?(k) }
      end
    end

    def notify_admin
      puts 'order cancelled'
    end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord

  belongs_to :order
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/dashboards_controller.rb
class DashboardsController < ApplicationController

  def show
    @klass = "myclass"
    @content = '<p>mon code</p>'
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def index
    @orders  = Order.all
  end

  def cancelleds
    LongJobJob.set(wait: 30.seconds).perform_later
    redirect_to orders_path
  end

  def show
    @order = Order.find params[:id]
    ActionCable.server.broadcast 'content_locking_channel', direction: 'lock', order_id: @order.id
  end

  def unlock
    @order = Order.find params[:id]
    ActionCable.server.broadcast 'content_locking_channel', direction: 'unlock', order_id: @order.id
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def main_sidebar_link *args, &block
    options = args.pop

    title = options.delete(:title)
    url = options.delete(:url)
    icon = options.delete(:icon)
    klass = options.delete(:class) || ''
    active = options.delete(:active) || ''

    if block
      content = capture(&block)
      if klass =~ /tree/
        add = content_tag('span', content_tag('i', '', class: 'fa fa-angle-left pull-right') , class: 'pull-right-container')
      end
      content_tag('li', link_to(content_tag('i','', class: "fa fa-#{icon}") + content_tag('span',title) + add, url, :title => title) + content, class: (klass + ' ' + active))
    else
      content_tag('li', link_to(content_tag('i','', class: "fa fa-#{icon}") + content_tag('span',title) , url, :title => title), class: (klass + ' ' + active))
    end
  end

  def info_box *args, &block
    options = args.pop

    title = options.delete(:title) || 'Title'
    indicator = options.delete(:indicator) || 0
    icon = options.delete(:icon)
    klass = options.delete(:class) || ''
    url = options.delete(:url) || ''
    active = options.delete(:active) || ''

    if block
      content = capture(&block)
    else
      content = ''
    end

    info_box_header = content_tag('div', content_tag('i','', class: 'fa fa-'+icon), class: 'info-box-icon ' + klass )

    span_text = content_tag('span', title, class: 'info-box-text')
    span_number = content_tag('span', indicator, class: 'info-box-number')
    info_box_content = content_tag('div', span_text + span_number + content , class: 'info-box-content')

    link_to content_tag('div', info_box_header + info_box_content, class: 'info-box'), url, style: "color: #333"
  end

  def breadcrumb_box items

    content = ''
    items.each do |item|
      content += content_tag('li', link_to( content_tag('i','', class: 'fa fa-' + item[:icon]) + item[:title], item[:url] ), class: (item == items.last && 'active'))
    end

    content_tag('ol', content.html_safe, class: 'breadcrumb')
  end

  def safe_html unsafe_html
    scrubber = Loofah::Scrubber.new do |node|
      node.remove if node.name == 'script'
    end

    sanitize unsafe_html, scrubber: scrubber
  end

end

app/helpers/dashboards_helper.rb
module DashboardsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/dashboards/show.html.haml
- @title = 'Dashboard'
- @page_title = 'Overview'
- @subtitle = ''

.box
  .box-header
    %h3.box-title Overview

    .pull-right
      %button.btn.btn-box-tool{ type: 'button', "data-widget": "collapse"}
        %i.fa.fa-minus

  .box-body
    %p Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{content: "text/html; charset=UTF-8", "http-equiv": "Content-Type"}/
    %title Keensaas
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body.hold-transition.skin-blue.sidebar-mini
    .wrapper
      = render 'shared/top_header'
      = render 'shared/left_menu'
      .content-wrapper
        = render 'shared/content_header'
        %section.content
          = yield
      = render 'shared/footer'

app/views/orders/_order.html.haml
%tr{ id: "order_#{order.id}"}
  %td= order.id
  %td= order.number
  %td= link_to "show", order_path(order), class: 'btn btn-small btn-primary'

app/views/orders/index.html.haml
- @title = 'Orders'
- @page_title = 'Orders'
- @subtitle = ''

.box
  .box-header
    %h3.box-title Orders

    .pull-right
      %button.btn.btn-box-tool{ type: 'button', "data-widget": "collapse"}
        %i.fa.fa-minus

  .box-body
    %table.table.table-bordered
      %thead
        %tr
          %th
            ID
          %th
            Number
          %th
            Actions
      %tbody
        = render partial: 'order', collection: @orders

app/views/orders/show.html.haml
%pre
  = @order.inspect

:javascript

  $(function(){

    $(window).on('beforeunload',function(){
      console.log('ok')
      $.ajax({
        type: 'GET',
        url: '#{unlock_order_path(@order)}',
        dataType: "json"
      })
    })
  })

app/views/shared/_content_header.html.haml
%section.content-header
  = yield :content_header
  %h1
    = @title
    %small
      = @subtitle
  %ol.breadcrumb
    /= render_breadcrumbs :tag => :li, :separator => ""

app/views/shared/_footer.html.haml
%footer.main-footer
  .pull-right.hidden-xs
    %b Version
    0.1
  %strong
    KEENSAAS Dashboard

app/views/shared/_left_menu.html.haml
%aside.main-sidebar
  %section.sidebar
    %ul.sidebar-menu{"data-widget" => "tree"}
      = main_sidebar_link title: 'DASHBOARD', url: "#", icon: 'tachometer', class: (@open_dashboards? 'treeview menu-open' : 'treeview'), active: (%w(admins).include?(controller_name) && 'active') do
        %ul.treeview-menu{style: (@open_dashboards && 'display:block;')}
          = main_sidebar_link title: 'Overview', url: root_path, icon: 'line-chart', active: (@current_page == root_url && "active")
          = main_sidebar_link title: 'Orders', url: orders_path, icon: 'line-chart', active: (@current_page == orders_url && "active")

app/views/shared/_top_header.html.haml
%header.main-header
  %a.logo{:href => root_path}
    %span.logo-mini
      %b> KEENSAASS

    %span.logo-lg

  %nav.navbar.navbar-static-top
    %a.sidebar-toggle{"data-toggle" => "push-menu", :href => "#", :role => "button"}
      %span.sr-only Toggle navigation
      %span.icon-bar
      %span.icon-bar
      %span.icon-bar
    

    .navbar-custom-menu
      -# %ul.nav.navbar-nav
      -#   %li.dropdown.user.user-menu
      -#     %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
      -#       %img.user-image{:alt => "User Image", :src => "https://www.gravatar.com/avatar/000000000000000000?f=y&d=mm"}/
      -#       %span.hidden-xs
      -#         = current_user.full_name
      -#     %ul.dropdown-menu
      -#       %li.user-header
      -#         %img.img-circle{:alt => "User Image", :src => "https://www.gravatar.com/avatar/000000000000000000?f=y&d=mm"}/
      -#         %p
      -#           = current_user.full_name
      -#       %li.user-footer
      -#
      -#         .pull-right
      -#           = link_to 'Sign out', destroy_user_session_path, :method => :delete, class: 'btn btn-default btn-flat'